### ISSUE TITLE
return http code 404 for the 404 resource

### ISSUE THREAD

**Issue by seebi** [AKSW/site.ontowiki#17]
see https://github.com/AKSW/OntoWiki/issues/228

**Comment by seebi** [comment]
please consider siteConfig.error resource too here

**Comment by seebi** [comment]
currently, ALL requests return a 404!

**Comment by yamalight** [comment]
@seebi okay, figured it out. that happens because of cache. if data is loaded from cache, SiteHelper->onIsDispatchable() always returns 404.
I have no idea how this $event thing works there, so please ask Jonas (who is to blame according to git blame) to change it so that it doesn't reacts to cache.
